# Site settings
title: Můj blog
email: email@domena.cz
description: > # this means to ignore newlines until "baseurl:"
  Popis stránek.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://username.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
